Check file type; check os; comments added.

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -11,6 +11,10 @@ formula="$1"
 version="$2"
 
 
+if [[ "$(uname -s)" != "Darwin" ]]; then
+	echo 'WARNING: it is recommented to run this script under macOS. not tested under other operating systems.'
+	exit 1
+fi
 if [ "${formula}" = "" ] || [ "${version}" = "" ]; then
 	echo "Usage: ${SCRIPT_BASENAME} <formula> <version>"
 	echo
@@ -19,11 +23,13 @@ if [ "${formula}" = "" ] || [ "${version}" = "" ]; then
 fi
 which sha256sum &> /dev/null || { echo 'ERROR: sha256sum not found in PATH'; exit 1; }
 which curl &> /dev/null || { echo 'ERROR: curl not found in PATH'; exit 1; }
+which stat &> /dev/null || { echo 'ERROR: stat not found in PATH'; exit 1; }
 
 set -e
 pushd "${SCRIPT_BASEDIR}/.."
 mkdir -p tmp
 
+# Create variables.
 vversion="v${version}"
 formula_file_path="${formula}.rb"
 formula_skel_file_path="skel/${formula_file_path}"
@@ -31,12 +37,27 @@ gz_file_name="${vversion}.tar.gz"
 tmp_gz_file_path="tmp/${gz_file_name}"
 url="${GITHUB_BASE_URL}/${formula}/archive/${gz_file_name}"
 
+# Download release file from GitHub.
 echo "download gz file '${url}'"
-curl -sSL -o "${tmp_gz_file_path}" "${url}"
+if ! curl -SL --ssl -o "${tmp_gz_file_path}" "${url}"; then
+	echo 'ERROR: curl failed'
+	exit 1
+fi
 
+# Make SHA256 hex for downloaded file.
 sha256hex=$(sha256sum "${tmp_gz_file_path}" | awk '{ print $1 }')
 echo "sha256 hex '${sha256hex}'"
 
+# Print file type.
+echo 'file type:'
+file "${tmp_gz_file_path}"
+if ! file "${tmp_gz_file_path}" | grep --silent 'gzip compressed data'; then
+	echo 'ERROR: file is wrong type'
+	exit 1
+fi
+
+# Create formula file from template (in skel/).
+echo "create ${formula_file_path}"
 sed -e "
 s|%VERSION%|${vversion}|g;
 s|%SHA256%|${sha256hex}|g;
